name: Update report data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1' # Mondays at 09:00 UTC

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run updater
        run: |
          python scripts/update_report_data.py
      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/report-data.json
            git commit -m "chore: refresh report-data.json from live sources"
            git push
          else
            echo "No changes to commit"
          fi
